name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update caniuse-lite
        run: npx update-browserslist-db@latest
        working-directory: ./mind-walk

      - name: Install dependencies
        run: npm install
        working-directory: ./mind-walk

      - name: Build the project
        run: npm run build
        working-directory: ./mind-walk

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting
        working-directory: ./mind-walk
